In [1]:
import numpy as np

### Create the dataset, an array from 1 to 9

In [4]:
data1D = np.arange(1,10)
print(data1D)

[1 2 3 4 5 6 7 8 9]


### Max of the array

In [5]:
data1D.max()

9

### Index with the maximum value

In [6]:
data1D.argmax()

8

### Min of the array

In [7]:
data1D.min()

1

### Index with the minimum value

In [8]:
data1D.argmin()

0

### Sum of the array

In [9]:
data1D.sum()

45

### Cumulative Sum of the array

In [10]:
print(data1D)
print(data1D.cumsum())

[1 2 3 4 5 6 7 8 9]
[ 1  3  6 10 15 21 28 36 45]


### Product of the array

In [12]:
data1D.prod()

362880

### Cumulative Product of the array

In [14]:
print(data1D.cumprod())

[     1      2      6     24    120    720   5040  40320 362880]


### Average - Mean of the array

In [17]:
data1D.mean()

5.0

### Variance of the array

In [18]:
data1D.var()

6.666666666666667

### Standard Deviation of the array

In [19]:
data1D.std()

2.5819888974716112

### 2 Dimensional Arrays
When we have 2D arrays, the same operations apply.  If the axis is not specified, the operations apply to the flattened array.  If the axis = 0 the operations apply for each column.  If the axis = 1, the operations apply for each row. 

In [21]:
data2D = np.array([[0,1,2],[3,4,5]])
print(data2D)

[[0 1 2]
 [3 4 5]]


### Sum of the whole array

In [22]:
data2D.sum()

15

### Sum of the columns of the whole array

In [24]:
print(data2D.sum(axis = 0))

[3 5 7]


### Sum of the rows of the whole array

In [25]:
print(data2D.sum(axis = 1))

[ 3 12]
