In [1]:
import numpy as np

### Create data array

In [10]:
data1D = np.arange(1,10)
print(data1D)

[1 2 3 4 5 6 7 8 9]


In [11]:
data2D = np.array([[0,1,2],[3,4,5]])
print(data2D)

[[0 1 2]
 [3 4 5]]


### Flattening an array

In [5]:
### by row, also the default
print(data2D.flatten('C')) # same as data2D.flatten() 
print(data2D.ravel('C'))

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [6]:
### by column
print(data2D.flatten('F'))
print(data2D.ravel('F'))

[0 3 1 4 2 5]
[0 3 1 4 2 5]


### Peak to Peak (maximum - minimum)

In [12]:
data1D.ptp()

8

### Reshape the array

In [14]:
# by row. The -1 has it autocalculate the second dimension
data1D.reshape(3,-1,order='C') # same as data.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# by column
data1D.reshape(3,-1,order='F')

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Shape of the array (# of rows, # of columns)

In [17]:
data2D.shape

(2, 3)