In [1]:
import numpy as np

### Create the data array

In [2]:
data1D = np.arange(1,10)
print(data1D)

[1 2 3 4 5 6 7 8 9]


In [5]:
data2D = np.array([[0,1,2],[3,4,5]])
print(data2D)

[[0 1 2]
 [3 4 5]]


### Dot product of two arrays

In [3]:
data1D.dot(data1D) ## 1*1 + 2*2 +3*3 + 4*4 + 5*5 + 6*6 + 7*7 + 8*8 + 9*9

285

### Transpose of an array

In [7]:
print(data2D.transpose())

[[0 3]
 [1 4]
 [2 5]]
